logging:
  level:
    root: INFO
    org:
      mariadb:
        jdbc: trace
      hibernate:
        SQL: trace
        type:
          descriptor:
            sql:
              BasicBinder: trace
          EnumType: trace
spring:
  datasource:
    url: jdbc:mariadb:aurora//127.0.0.1:3306/your_schema?log=true&profileSQL=true&traceProtocol=true
    username: root
    password: your_password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop